name: Release
on:
  push:
    tags:
      # Push events to matching v*, i.e. v1.0, v20.15.10
      - v*

  workflow_dispatch:
    inputs:
      version:
        default: 'latest'
        required: true
        type: string

env:
  version: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || inputs.version }}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: [8.0.x]

    - name: Restore products
      # run: dotnet restore
      run: dotnet restore .\Randoom\Randoom.csproj

    - name: Build
      # run: dotnet build --configuration Release --no-restore
      run: dotnet build --configuration Release --no-restore -f net8.0 .\Randoom\Randoom.csproj

    - name: Zip the Build
      # Windows tar tool.
      # run: tar -cvf Randoom.${{ env.version }}.net8.tar.gz -C'bin\Release\net8.0' .
      # Windows powershell.
      run: Compress-Archive -Path bin\Release\net8.0\*.* -DestinationPath Randoom.${{ env.version }}.net8.zip

    - name: Create Release and upload files
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.version }}
        name: ${{ env.version }}
        body: Randoom DEMO with lib Honoo.Randoom.dll.
        draft: false
        prerelease: false
        files: |
          Randoom.${{ env.version }}.net8.zip