name: Release
on:
  push:
    tags:
      - v* # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:
    inputs:
      version:
        default: 'latest'
        required: true
        type: string

env:
  version: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || inputs.version }}
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore products
      run: dotnet restore .\Randoom\Randoom.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore -f net8.0 .\Randoom\Randoom.csproj
      
    - name: Zip the Build
      # run: tar -cvf Randoom.net8.tar.gz -C'bin\Release\net8.0' .
      run: Compress-Archive -Path bin\Release\net8.0\*.* -DestinationPath Randoom.${{ env.version }}.net8.zip

    - name: Create and upload Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: $env.version
        name: ${{ env.version }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          Randoom.${{ env.version }}.net8.zip