name: Release
on:
  push:
    tags:
      - v* # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:
    inputs:
      version:
        default: 'latest'
        required: true
        type: string

env:
  if: ${{ startsWith(github.ref, 'refs/tags/') }}
  version: ${{ github.ref_name }}
  if: ${{ !startsWith(github.ref, 'refs/tags/') }}
  version: ${{ inputs.version }}
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore products
      run: dotnet restore .\Randoom\Randoom.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore -f net8.0 .\Randoom\Randoom.csproj
      
    - name: Zip the Build
      # run: tar -cvf Randoom.net8.tar.gz -C'bin\Release\net8.0' .
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r Randoom.net8.zip bin\Release\net8.0

    - name: Create and upload Release on push
      uses: softprops/action-gh-release@v2
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          Randoom.net8.zip

    - name: Create and upload Release on workflow_dispatch
      uses: softprops/action-gh-release@v2
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      with:
        tag_name: $env.version
        name: ${{ env.version }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          Randoom.net8.zip