name: Release
on:
  push:
    tags:
      - v* # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:
    inputs:
      tag:
        description: 'Setup version tag'
        default: 'latest'
        required: true
        type: string

env:
  tag: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || inputs.tag }}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore products
      run: dotnet restore .\Randoom\Randoom.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore -f net8.0 .\Randoom\Randoom.csproj

    - name: Zip the Build
      # run: tar -cvf Randoom.${{ env.tag }}.net8.tar.gz -C'bin\Release\net8.0' .
      run: Compress-Archive -Path bin\Release\net8.0\*.* -DestinationPath Randoom.${{ env.tag }}.net8.zip

    - name: Create Release and upload files
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.tag }}
        name: Randoom demo
        body: Randoom demo with lib Honoo.Randoom.dll.
        draft: false
        prerelease: false
        files: |
          Randoom.${{ env.tag }}.net8.zip